### ISSUE TITLE
regarding the python app.py

### ISSUE THREAD

**Issue by kashyaprakshith** [ShreyanshJoshi/Facial-Demographics-using-CNN#1]
i followed the steps given in the readme file, i wasnt able to find the app.py file, which seems to be important as it contains many important files, please revert back as soon as possible

**Comment by ShreyanshJoshi** [comment]
Go  to Deployment, followed by one of the 2 folders that you want to clone/ test the code locally. There you will find the app.py file for that task.

**Comment by kashyaprakshith** [comment]
got it!!!
Thank you!!

**Comment by ShreyanshJoshi** [comment]
Btw, pls consider starring/forking the repo, if my code helped you in any way.

**Comment by kashyaprakshith** [comment]
yes!! of course thats for sure!!
