### ISSUE TITLE
regarding the wiki.mat file

### ISSUE THREAD

**Issue by kashyaprakshith** [ShreyanshJoshi/Facial-Demographics-using-CNN#2]
i think the repository is missing the wiki.mat matlab file, i tried running the code in google collab it is throwing an error stating that       
"unzip:  cannot find or open /content/drive/My Drive/wiki_crop.zip, /content/drive/My Drive/wiki_crop.zip.zip or /content/drive/My Drive/wiki_crop.zip.ZIP.", i think the files that needs to be unzipped is not uploaded.
please revert as soon as possible.

**Comment by ShreyanshJoshi** [comment]
Well, you can find that file (dataset) - wiki_crop.zip online. I'm not sure if I still have it. We can't upload files of datasets on github without permissions and proper rights.

**Comment by kashyaprakshith** [comment]
ooh alright thanks man!!
