### ISSUE TITLE
regarding the folder "images"

### ISSUE THREAD

**Issue by kashyaprakshith** [ShreyanshJoshi/Facial-Demographics-using-CNN#3]
hello!!
in the code containing both age and gender classification, i think you have created a statistical information about the images, contauining labels, race , gender, age, etc. did you put the images in the datasets or a certain set of your images?,
 please revert back!!...

**Comment by ShreyanshJoshi** [comment]
No, I did not make any changes to the dataset per se, as far as I remember. However, I indeed tried augmenting our dataset while training, by inbuilt functions of Keras.

**Comment by kashyaprakshith** [comment]
thanks!! got it!!!
