### ISSUE TITLE
reagrding the value error thrown in age and gender classification.ipynb

### ISSUE THREAD

**Issue by kashyaprakshith** [ShreyanshJoshi/Facial-Demographics-using-CNN#4]
![Screenshot from 2021-06-01 19-14-09](https://user-images.githubusercontent.com/58388399/120365184-69633580-c30e-11eb-9d29-748b82d80ffc.png)
the "ValueError: classes should have valid labels that are in y" is thrown, i think there needs a manipulation in packages i.e class_weights.py, had you got this issue while writing the code,should we convert dataframe into an array?i have attached a snap of the error beingh raised, if you know how to debug it please revert back soon....

**Comment by ShreyanshJoshi** [comment]
Hey, i am really sorry, I am very busy these days. Hence would not be able to debug the code for you. You should be able to find solutions in stackoverflow or some other website though.

**Comment by kashyaprakshith** [comment]
hey!!! yes i could debug it!!, a very beautifully written code brother, detailed analysis of the data is a new insight........

**Comment by ShreyanshJoshi** [comment]
Glad my code helped you :)
